# Generated by Django 5.2.12 on 2026-03-23 15:14

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lapso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Lapso',
                'verbose_name_plural': 'Lapsos',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('excerpt', models.TextField(blank=True, help_text='Resumen corto que se muestra en las tarjetas del listado.', max_length=500, verbose_name='Extracto')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Contenido')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='posts/featured/', verbose_name='Imagen destacada')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publicado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('lapso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blog.lapso', verbose_name='Lapso')),
            ],
            options={
                'verbose_name': 'Publicación',
                'verbose_name_plural': 'Publicaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MediaAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Imagen'), ('video', 'Video'), ('document', 'Documento')], default='image', max_length=10, verbose_name='Tipo de medio')),
                ('file', models.FileField(blank=True, help_text='Sube una imagen, video o documento.', null=True, upload_to='posts/media/', verbose_name='Archivo')),
                ('external_url', models.URLField(blank=True, help_text='URL de YouTube, Vimeo u otra plataforma para incrustar.', verbose_name='URL externa')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Descripción')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_attachments', to='blog.post', verbose_name='Publicación')),
            ],
            options={
                'verbose_name': 'Archivo multimedia',
                'verbose_name_plural': 'Archivos multimedia',
                'ordering': ['order'],
            },
        ),
    ]
