# Generated by Django 5.2.12 on 2026-03-23 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaattachment',
            name='file',
            field=models.FileField(blank=True, help_text='Formatos aceptados: imágenes (JPG, PNG), videos (MP4, AVI), PDF, Word, Excel, PowerPoint.', null=True, upload_to='posts/media/', verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='mediaattachment',
            name='media_type',
            field=models.CharField(choices=[('image', 'Imagen'), ('video', 'Video'), ('pdf', 'PDF'), ('word', 'Word (DOC/DOCX)'), ('powerpoint', 'PowerPoint (PPT/PPTX)'), ('excel', 'Excel (XLS/XLSX)'), ('document', 'Otro documento')], default='image', max_length=12, verbose_name='Tipo de medio'),
        ),
    ]
