# Generated by Django 5.2.12 on 2026-05-06 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_mediaattachment_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaattachment',
            name='external_url',
            field=models.URLField(blank=True, help_text='URL de YouTube, Vimeo u otra plataforma para incrustar.', max_length=2000, verbose_name='URL externa'),
        ),
        migrations.AlterField(
            model_name='mediaattachment',
            name='file',
            field=models.FileField(blank=True, help_text='Formatos aceptados: imágenes (JPG, PNG), videos (MP4, AVI), PDF, Word, Excel, PowerPoint.', max_length=500, null=True, upload_to='posts/media/', verbose_name='Archivo'),
        ),
    ]
